spring:
  application:
    name: kafka-flink-processing
  kafka:
    bootstrap-servers:
      - localhost:9093
      - localhost:9094
      - localhost:9095
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted.packages: "*"
    topic:
      name: users
server:
  port: 8080
  servlet:
    context-path: /api
